name: cno-solar
channels:
  - conda-forge
dependencies:
  - pvlib-python==0.9.0
  - matplotlib==3.1.1
  - jsonschema==4.16.0
  - jupyterlab==3.4.4
  - ipykernel==6.15.2
  - tqdm==4.36.1
  - ipywidgets==7.5.1
  - pip==21.2.4
  - pip:
    - nrel-pysam==3.0.2
    - pvfactors==1.5.1
