name: cno-solar
channels:
  - conda-forge
dependencies:
  - pvlib-python==0.9.3
  - matplotlib==3.6.0
  - jsonschema==4.16.0
  - jupyterlab==3.4.7
  - ipykernel==6.9.1
  - tqdm==4.64.1
  - ipywidgets==7.7.1
  - pip==21.2.4
  - pip:
    - nrel-pysam==3.0.2
    - pvfactors==1.5.2